export const DEFAULT_VALUES = {
  Age: 25,
  Gender: "Male",
  "Weight (kg)": 75,
  "Height (m)": 1.75,
  Max_BPM: 180,
  Avg_BPM: 145,
  Resting_BPM: 65,
  "Session_Duration (hours)": 1,
  Fat_Percentage: 20,
  "Water_Intake (liters)": 2.5,
  "Workout_Frequency (days/week)": 4,
  Experience_Level: 2,
  BMI: 24.49,
  Workout_Type: "HIIT",
};

export const SLIDERS = [
  {
    name: "Age",
    label: "Age",
    min: 18,
    max: 59,
    step: 1,
    suffix: " yrs",
  },
  {
    name: "Weight (kg)",
    label: "Weight",
    min: 40,
    max: 129.9,
    step: 0.1,
    suffix: " kg",
  },
  {
    name: "Height (m)",
    label: "Height",
    min: 1.5,
    max: 2.0,
    step: 0.01,
    suffix: " m",
  },
  {
    name: "Max_BPM",
    label: "Max BPM",
    min: 160,
    max: 199,
    step: 1,
    suffix: " BPM",
  },
  {
    name: "Avg_BPM",
    label: "Average BPM",
    min: 120,
    max: 169,
    step: 1,
    suffix: " BPM",
  },
  {
    name: "Resting_BPM",
    label: "Resting BPM",
    min: 50,
    max: 74,
    step: 1,
    suffix: " BPM",
  },
  {
    name: "Session_Duration (hours)",
    label: "Session Duration",
    min: 0.5,
    max: 2.0,
    step: 0.05,
    suffix: " hr",
  },
  {
    name: "Fat_Percentage",
    label: "Body Fat",
    min: 10,
    max: 35,
    step: 0.1,
    suffix: "%",
  },
  {
    name: "Water_Intake (liters)",
    label: "Water Intake",
    min: 1.5,
    max: 3.7,
    step: 0.1,
    suffix: " L",
  },
  {
    name: "Workout_Frequency (days/week)",
    label: "Workout Frequency",
    min: 2,
    max: 5,
    step: 1,
    suffix: " days/week",
  },
];

export const SELECTS = [
  {
    name: "Gender",
    label: "Gender",
    options: ["Female", "Male"],
  },
  {
    name: "Workout_Type",
    label: "Workout Type",
    options: ["Cardio", "HIIT", "Strength", "Yoga"],
  },
  {
    name: "Experience_Level",
    label: "Experience Level",
    options: [
      { label: "Beginner", value: 1 },
      { label: "Intermediate", value: 2 },
      { label: "Advanced", value: 3 },
    ],
  },
];
